export default function ReportsPage() {
  return (
    <main className="mx-auto max-w-4xl p-6">
      <h1 className="text-2xl font-semibold text-slate-900">Reports & analytics</h1>
      <p className="mt-2 text-slate-600">
        Weekly safety reports and platform rollups are generated by secure cron endpoints.
      </p>
      <ul className="mt-4 list-disc pl-6 text-slate-700">
        <li>/api/cron/weekly-reports</li>
        <li>/api/cron/analytics-rollup</li>
        <li>/api/cron/risk-snapshots</li>
        <li>/api/cron/risk-thresholds</li>
      </ul>
    </main>
  );
}
